[tool.poetry]
name = "cumulus-message-adapter-passthrough"
version = "2.4.0a9"

description = "A simple lambda which pass input through output"
authors = ["PODAAC IngestAndArchive <podaac@jpl.nasa.gov>"]

[tool.poetry.dependencies]
python = "^3.12"
cumulus-process = "1.7.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.masonry.api"
